# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7k70tfbv676-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir {C:/term 2/micro/Mano-Basic-Computer-Using-Verilog-main/Mano-Basic-Computer-Using-Verilog-main/project_1/project_1.cache/wt} [current_project]
set_property parent.project_path {C:/term 2/micro/Mano-Basic-Computer-Using-Verilog-main/Mano-Basic-Computer-Using-Verilog-main/project_1/project_1.xpr} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  {C:/term 2/micro/Mano-Basic-Computer-Using-Verilog-main/Mano-Basic-Computer-Using-Verilog-main/project_1/project_1.srcs/sources_1/new/256_RAM.v}
  {C:/term 2/micro/Mano-Basic-Computer-Using-Verilog-main/Mano-Basic-Computer-Using-Verilog-main/project_1/project_1.srcs/sources_1/new/AC_CONTROL.v}
  {C:/term 2/micro/Mano-Basic-Computer-Using-Verilog-main/Mano-Basic-Computer-Using-Verilog-main/project_1/project_1.srcs/sources_1/new/AC_REG.v}
  {C:/term 2/micro/Mano-Basic-Computer-Using-Verilog-main/Mano-Basic-Computer-Using-Verilog-main/project_1/project_1.srcs/sources_1/new/AC_adderNlogic.v}
  {C:/term 2/micro/Mano-Basic-Computer-Using-Verilog-main/Mano-Basic-Computer-Using-Verilog-main/project_1/project_1.srcs/sources_1/new/AR _Control.v}
  {C:/term 2/micro/Mano-Basic-Computer-Using-Verilog-main/Mano-Basic-Computer-Using-Verilog-main/project_1/project_1.srcs/sources_1/new/BUS_Control.v}
  {C:/term 2/micro/Mano-Basic-Computer-Using-Verilog-main/Mano-Basic-Computer-Using-Verilog-main/project_1/project_1.srcs/sources_1/new/Control_Unit.v}
  {C:/term 2/micro/Mano-Basic-Computer-Using-Verilog-main/Mano-Basic-Computer-Using-Verilog-main/project_1/project_1.srcs/sources_1/new/DR_Control.v}
  {C:/term 2/micro/Mano-Basic-Computer-Using-Verilog-main/Mano-Basic-Computer-Using-Verilog-main/project_1/project_1.srcs/sources_1/new/Decoder3x8.v}
  {C:/term 2/micro/Mano-Basic-Computer-Using-Verilog-main/Mano-Basic-Computer-Using-Verilog-main/project_1/project_1.srcs/sources_1/new/Encoder8x3.v}
  {C:/term 2/micro/Mano-Basic-Computer-Using-Verilog-main/Mano-Basic-Computer-Using-Verilog-main/project_1/project_1.srcs/sources_1/new/IR_Control.v}
  {C:/term 2/micro/Mano-Basic-Computer-Using-Verilog-main/Mano-Basic-Computer-Using-Verilog-main/project_1/project_1.srcs/sources_1/new/MUX8_x3.v}
  {C:/term 2/micro/Mano-Basic-Computer-Using-Verilog-main/Mano-Basic-Computer-Using-Verilog-main/project_1/project_1.srcs/sources_1/new/Memory_control.v}
  {C:/term 2/micro/Mano-Basic-Computer-Using-Verilog-main/Mano-Basic-Computer-Using-Verilog-main/project_1/project_1.srcs/sources_1/new/PC_REG.v}
  {C:/term 2/micro/Mano-Basic-Computer-Using-Verilog-main/Mano-Basic-Computer-Using-Verilog-main/project_1/project_1.srcs/sources_1/new/PC_control.v}
  {C:/term 2/micro/Mano-Basic-Computer-Using-Verilog-main/Mano-Basic-Computer-Using-Verilog-main/project_1/project_1.srcs/sources_1/new/Sequence_counter.v}
  {C:/term 2/micro/Mano-Basic-Computer-Using-Verilog-main/Mano-Basic-Computer-Using-Verilog-main/project_1/project_1.srcs/sources_1/new/seq_counter.v}
  {C:/term 2/micro/Mano-Basic-Computer-Using-Verilog-main/Mano-Basic-Computer-Using-Verilog-main/project_1/project_1.srcs/sources_1/new/main.v}
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
set_param ips.enableIPCacheLiteLoad 0
close [open __synthesis_is_running__ w]

synth_design -top Mainn -part xc7k70tfbv676-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef Mainn.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file Mainn_utilization_synth.rpt -pb Mainn_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
